---
title: "GenresComparison"
output: html_notebook
---


```{r}
library(tidyverse)
```

```{r}
genres_data <- read_csv('musical_artist.genres.csv')
```
select genres and create new data set with chosen genres
```{r}
genres_grouped <- genres_data %>%
  group_by(genre)

selected_genres<- genres_grouped %>%
    mutate(
    genre_category = case_when(
      str_detect(genre, "rock") | str_detect(genre, "Rock") ~ "Rock",
      str_detect(genre, "bebop") |  str_detect(genre, "Bebop") ~ "Bebop",
      str_detect(genre, "classical") |  str_detect(genre, "Calssical") ~ "Classical",
      str_detect(genre, "pop") |  str_detect(genre, "Pop") ~ "Pop",
      str_detect(genre, "blues") |  str_detect(genre, "Blues") ~ "Blues",
      str_detect(genre, "jazz") |  str_detect(genre, "Jazz") ~ "Jazz",
      str_detect(genre, "country") |  str_detect(genre, "Country") ~ "Country",
      str_detect(genre, "folk") |  str_detect(genre, "Folk") ~ "Folk",
      str_detect(genre, "gospel") |  str_detect(genre, "Gospel") ~ "Gospel"
    )
  ) %>%
  filter(!is.na(genre_category))
  
  # filter(str_detect(genre, "rock") | str_detect(genre, "Rock"))
  
```

calculate average age of death of every genre
```{r}
genres_and_age <- selected_genres %>%
  mutate(
    age = as.numeric(deathYear) - birthYear) %>%
   filter(birthYear >= 1815) %>% 
  filter(deathYear > as.numeric(birthYear)) %>%
  filter(age>5) %>%
  filter(age<110) %>%
  filter(birthYear <= 2019)%>%
  group_by(genre_category) 

genre_avg_age <- genres_and_age %>%
  filter(birthYear <= 1950) %>%
  summarise(mean_age = mean(age))
   
```


create graph

```{r}
ggplot(data = genre_avg_age, aes( fill= genre_category, x= reorder(genre_category, -mean_age), y = mean_age) )+
  geom_bar(position='dodge', stat = "identity")+
   xlab("Categories") + ylab("Mean Age") +
  labs(fill = 'Genre\n') +
ggtitle("Comparison of Average Age of death of Artists by Genres")

ggsave("DeathByGenre.png")


```

Extend to 27 club 

```{r}
genres_age_27 <- selected_genres %>%
  mutate(
    age = as.numeric(deathYear) - birthYear) %>%
  filter(birthYear >= 1815) %>% 
  filter(deathYear > as.numeric(birthYear)) %>%
  filter(age<28) %>%
  filter(birthYear < 2019) %>%
  group_by(genre_category) 


```

```{r}
ggplot(data = genres_age_27, aes(genre_category, fill = genre_category)) +
  geom_bar(position = "dodge") +
   xlab("Categories") + ylab("Number of deaths before age of 27") +
  labs(fill = 'Genre\n') +
ggtitle("Comparison of number of deaths before the age of 27 of Artists by Genres")
ggsave("Death27ByGenre.png")


```

Create proportional club 27 graph 

```{r}
genre_27_proportion <- genres_and_age %>%
  mutate(yesno_27 = ifelse(age < 28,'club27','neee')) %>%
  group_by(genre_category, yesno_27) %>%
  summarise(count = n()) %>%
  pivot_wider(names_from = yesno_27, values_from = count) %>%
  mutate(proportion = (club27/(club27 + neee))*100) 
```


```{r}
ggplot(data = genre_27_proportion, aes(fill = genre_category, x = genre_category, y = proportion)) +
  geom_bar(position = "dodge", stat = "identity") +
   xlab("Categories") + ylab("Percentage of deaths before age of 27 from each Genre") +
  labs(fill = 'Genre\n') +
ggtitle("Proportion of deaths before the age of 27 of Artists by Genres") +
ggsave("Death27ByGenre.png")
 
```







